# Dictionary that maps each book of the Bible to their abbreviatons
bible = {
    'acts': ['act', 'ac', 'acta', 'acts'],
    'amos': ['am', 'amos'],
    'baruch': ['bar', 'baruch'],
    'canticles': ['cant', 'cantic', 'canticle', 'cantica', 'carm', 'canticles'],
    'chronicles': ['chron', 'chr', 'ch', 'chro', 'chronicles'], # deleted "or"
    'colossians': ['col', 'coloss', 'colos', 'colossians'], 
    'corinthians': ['cor', 'co', 'cr', 'corinth', 'corin', 'corinthians'],
    'daniel': ['dan', 'da', 'dn', 'daniel'],
    'deuteronomy': ['deut', 'de', 'dt', 'deu', 'deuter', 'dut', 'deuteronomy'],
    'ecclesiastes': ['eccles', 'eccl', 'eccle', 'ecc', 'ec', 'ecls', 'ecles', 'eccls', 'eecles', 'ecclesiastes'],
    'ecclesiasticus': ['ecclus', 'ecclesiasticus'],
    'ephesians': ['eph', 'ephes', 'ephe', 'ephs', 'ehes', 'ephesians'],
    'epistle': ['ep', 'epist', 'epist', 'epistle'],
    'esther': ['est', 'esth', 'es', 'ester', 'esther'],
    'exodus': ['ex', 'exod', 'exo', 'exodus'],
    'ezekiel': ['ezek', 'eze', 'ezk', 'ezech', 'ezck', 'ezec', 'ezekiel'],
    'ezra': ['ezr', 'ez', 'ezra'],
    'galatians': ['gal', 'ga', 'galat', 'galatians'],
    'genesis': ['gen', 'gens', 'ge', 'gn', 'genes', 'gene', 'genesis'],
    'habakkuk': ['hab', 'hb', 'habb', 'habbak', 'habba', 'habbac', 'habac', 'abakk', 'habakkuk'],
    'haggai': ['hag', 'hg', 'hagg', 'haggai'],
    'hebrews': ['heb', 'hebr', 'hebrews'],
    'hosea': ['hos', 'ho', 'hoshea', 'hosh', 'hose', 'hsea', 'hsh', 'hosea'],
    'isaiah': ['isa', 'isai', 'isay', 'es', 'esi', 'esa', 'esai', 'esay', 'esaiae', 'esal', 'isaiah'],
    'james': ['jas', 'jm', 'iam', 'iams', 'ias', 'im', 'iames', 'jam', 'iaes', 'james'],
    'jeremiah': ['jer', 'je', 'jr', 'ier', 'ie', 'ir', 'ieremiah', 'ierem', 'erem', 'jerem', 'ierm', 'iere', 'jeremiah'],
    'job': ['job', 'jb', 'iob', 'ib', 'job'],
    'joel': ['jl', 'ioel', 'il', 'joel'],
    'john': ['joh', 'jhn', 'ioh', 'ihn', 'iohn', 'ioan', 'joan', 'john'],
    'jonah': ['jnh', 'jon', 'ion', 'inh', 'ionah', 'jona', 'iona', 'jonah'],
    'joshua': ['josh', 'iosh', 'jos', 'ios', 'jsh', 'ish', 'ioshua', 'iosua', 'josua', 'iosu', 'joshua'],
    'jude': ['jud', 'jd', 'iud', 'id', 'iude', 'jude'],
    'judges': ['judg', 'jdg', 'jg', 'jdgs', 'iudg', 'idg', 'ig', 'idgs', 'iudges', 'judges'],
    'judith': ['jth', 'jdth', 'jdt', 'ith', 'idth', 'idt', 'iudith', 'judith'],
    'kings': ['kin', 'king', 'knig', 'kinges', 'kings'],
    'lamentations': ['lam', 'la', 'lament', 'lamnt', 'lamentations'],
    'leviticus': ['lev', 'le', 'lv', 'lu', 'leu', 'leuiticus', 'leuit', 'levit', 'leviticus'],
    'luke': ['luk', 'lk', 'luc', 'lc', 'luke'],
    'malachi': ['mal', 'ml', 'malac', 'malach', 'mala', 'malachi'],
    'mark': ['mrk', 'mar', 'mk', 'mr', 'marc', 'marke', 'mark'],
    'matthew': ['matt', 'matth', 'mt', 'math', 'mat', 'mattth', 'mattb', 'matthew'],
    'micah': ['mic', 'mc', 'mica', 'micha', 'micah'],
    'nahum': ['na', 'nah', 'nahum'],
    'nehemiah': ['neh', 'ne', 'nehem', 'nehe', 'nehemiah'],
    'numbers': ['num', 'nu', 'nm', 'numb', 'nb', 'numbers'],
    'obadiah': ['obad', 'ob', 'obadiah'],
    'peter': ['pet', 'pe', 'pt', 'p', 'petr', 'peter'],
    'philemon': ['philem', 'phm', 'pm', 'philemon'],
    'philippians': ['phil', 'php', 'pp', 'phillip', 'philip', 'hilip', 'phi', 'philippians'],
    'proverbs': ['prov', 'pro', 'prv', 'pr', 'prou', 'pru', 'prouerb', 'prouerbs', 'pou', 'pov', 'proverb', 'proverbs'],
    'psalms': ['ps', 'psalm', 'psl', 'pslm', 'psa', 'psm', 'pss', 'psal', 'psalme', 'psol', 'psalms'],
    'revelation': ['rev', 're', 'reu', 'reuelation', 'reuel', 'reuelations', 'reve', 'revel', 'apoc', 'apo', 'revelation'],
    'romans': ['rom', 'ro', 'rm', 'roman', 'romans'],
    'ruth': ['ruth', 'rth', 'ru', 'ruth'],
    'samuel': ['samuell', 'sam', 'sm', 'samuel'],
    'thessalonians': ['thess', 'thes', 'th', 'thss', 'thoss', 'thessalonians'],
    'timothy': ['tim', 'timoth', 'tom', 'timo', 'timothy'],
    'titus': ['tit', 'tius', 'titus'],
    'tobit': ['tob', 'tobi', 'tobit'],
    'zechariah': ['zech', 'zec', 'zc', 'zch', 'zach', 'zachar', 'zac', 'zechariah'],
    'zephaniah': ['zeph', 'zep', 'zp', 'zephan', 'zephaniah'],
}

# Turn the numbered books into one word for convenience in later regex tasks 
numBook = {
    '1 samuel':'onesamuel',
    '2 samuel':'twosamuel',
    '1 kings':'onekings',
    '2 kings':'twokings',
    '1 chronicles':'onechronicles',
    '2 chronicles':'twochronicles',
    '1 corinthians':'onecorinthians',
    '2 corinthians':'twocorinthians',
    '1 thessalonians':'onethessalonians',
    '2 thessalonians':'twothessalonians',
    '1 timothy':'onetimothy',
    '2 timothy':'twotimothy',
    '1 peter':'onepeter',
    '2 peter':'twopeter',
    '1 john':'onejohn',
    '2 john':'twojohn',
    '3 john':'threejohn'
}

