
'''Standardization dictionaries'''
# Dictionary that maps each book of the Bible and the Apocrypha to their abbreviatons
abbrev = {
    'acts': ['acta', 'acts', 'act', 'ac','actes','aact'],
    # Mos? 
    'amos': ['am', 'amos','amo','amoz'],
    'baruch': ['baruch', 'bar','baruc','baru','br','baruck','bart'],
    # A96530,sermon,375,81,"Song of Sol. 2. 1, 2."
    'canticles': ['cant', 'cantic', 'canticles', 'canticle','canticae',
                  'song','songs'], 
    'chronicles': ['chron', 'chro', 'chr', 'chronicles', 'ch',
                   'cron','chr*n','chroni','cro','chrou','chro*'],
    'colossians': ['colossians', 'colos', 'col', 'coloss','col*ss',
                   'coles','coless','coll','collo','collos','colloss',
                   'colo','colossi','coss'],
    'corinthians': ['corinth', 'corin', 'corinthians', 'cor','c*r',
                    'co*in','corint','corr','cors','couinth','co',
                    'corinthes','cour'],
    'daniel': ['dan', 'daniel', 'dn', 'da','d*n','dani','danie',
               'daniell','den','din','don','dun','daniele'],
    'deuteronomy': ['deu', 'de', 'dt', 'dut', 'deuteronomy', 'deuter', 
                    'deut','d*t','d*ut','dcut','det','detr','deue',
                    'deuer','deur','deute','deutero','deutr','deutro',
                    'deutrono','dout','duet','deuteronomie'],
    'ecclesiastes': ['eecles', 'eccl', 'ecc', 'ecls', 'eccle', 'ecles',
                     'eccls', 'eccles', 'ecclesiastes','e*cles','ec*les',
                     'ecc*es','ecc*s','ecccles','ecce','ecces','ecclas',
                     'ecclesi','ecclesias','ecclesiast','eccless','ecclf',
                     'eccli','ecclis','eceles','ecl','ecle','eecl','excles',
                     'fccles','fecles','ec','ecclesiaste'],
    # ambiguous: 'eccl*s'
    'ecclesiasticus': ['ecclesiasticus', 'ecclus','ecclesiastic','ec*lus',
                       'ecceus','eccus','eclus','eccius','eccsus'],
    'ephesians': ['ephe', 'eph', 'ephes', 'ehes', 'ephs', 'ephesians',
                  'e*hes','e*ph','ehe','ehpes','ep*es','eph*s','ephc',
                  'ephef','ephese','ephesi','ephis','ephos','epht'],
    'epistle': ['ep', 'epistle', 'epist','eppes','epb','epi','epict',
                'epis','epl','ept'],
    'esther': ['ester', 'es', 'est', 'esther', 'esth','esd','esdt',
               'ess','est','est*r','esr','este','esth*r','et','eth',
               'esdr'],
    'exodus': ['exod', 'exodus', 'exo', 'ex','eod','exdo','exe','exob',
               'exoe','*xod'],
    'ezekiel': ['ezck', 'ezk', 'ezek', 'ezec', 'eze', 'ezekiel', 'ezech',
                'aezek','eek','eezk','esech','enech','exech','ez*ch','ez*k',
                'ez*kiel','ezach','ezc','ezch','ezechi','ezechiel','ezeck',
                'ezeh','ezel','ezeth','ezez','ezik','ezke','ezo','ezok',
                'ezekiell'],
    'ezra': ['ezra', 'ez', 'ezr','era','ezrae','ezrah','ezras','esra'],
    'galatians': ['galatians', 'gal', 'ga', 'galat','gae','gai','gala',
                  'galath','gall','galla','gallat','golat','gael',
                  'gas','gea','gla','gan','gad','gan','gra'],
    'genesis': ['genesis', 'gen', 'gens', 'ge', 'genes', 'gene', 'gn','genr',
                'ge*','geneses','g*n','geen','gen*s','genc','geu','gon','rgen'],
    'habakkuk': ['habb', 'habba', 'hb', 'abakk', 'habbac', 'habakkuk', 'hab', 
                'habbak', 'habac','hab','abac','abak','h*b','ha','haba',
                'habab','habacuk','habak','habr','habuc','hcb','halac',
                'hcb','hib'], # halac?
    'haggai': ['hagg', 'hg', 'haggai', 'hag','ag','agg','hagga','hagge','haggi'],
    'hebrews': ['hebrews', 'hebr', 'heb','*ebr','eb','he','hebra','hebre',
                'hebrewes','hebru'],
    'hosea': ['hosea', 'hose', 'hoshea', 'hosh', 'hos', 'ho', 'hoses',
              'h*sea','ho*ea','hoa','hos*a','hosa','hosc','hosca',
              'hoseah','hoseas','hosee','host','hs','os','ose',
              'osea','oseah','oseas'],
    'isaiah': ['esay', 'jsaiah', 'esal', 'esaiae', 'jsay', 'esai', 'jsa', 
               'esa', 'jsai', 'esi','esaie','esaias','jsaie','e*ay','ysaie',
               'aiah','eay','eisai','es*i','esaia','esaiah','esaie','esar',
               'esau','esih','j*sa','ja','js','jsaai','jsah','jsaia',
               'jsaiae','jsaias','jsaih','jsal','jsalah','jsam','jsas',
               'jsat','jsi','ysaiah'],
    'james': ['jam', 'jm', 'jams', 'james', 'jas', 'jame','jamis',
              'j*am','j*m','j*mes','jam*s','jame','jeam','jim','jom'],
    'jeremiah': ['je', 'jerem', 'jeremiah', 'jere', 'jr', 'jerm', 
                 'jer','hierem','hieremiah','j*r','j*rem','je*em',
                 'jeh','jer*m','jeramiah','jerc','jercm','jeremi',
                 'jeremia','jeremie','jeremy','jereniah','jero',
                 'jerom','jor','jorem','jexem','jet'],
    'job': ['jb', 'job','lob','jobe','j*b','jab','jo','jobi','jobn'], # ihb? Josb? 
    'joel': ['jl', 'joel','joell','j*l','jal','jol','jul'],
    'john': ['john', 'joan', 'joh','jhon','jn*','jn*','joane','jone','jhu',
             'johes','johis','j*hn','jhon','jh','jo*n','joa','joann',
             'joans','joha','johan','johh','johon','johu','jonan'], 
             # see St.-Joh.
             # ambiguous jo*n, johah  
    'jonah': ['jonah', 'jona', 'jon','jo*ah','jo*n','jonab',
              'jonak','jonas','jonath','jonoh'],
    'joshua': ['josh', 'jos', 'jsh', 'josua', 'joshua', 'josu','josue',
               'jo*h','jshua','joes','jose','joshu','joshuah','jossh',
               'josuah','josue','jou'],
    'jude': ['jud', 'jd', 'jude','j*d','jod','ju','juda','judae'],
    # ambiguous judi, judie 
    'judges': ['judges', 'jg', 'judg','judge','j*dg','jug','juge'],
    'judith': ['judith', 'jth', 'judeth','judi','judie','judit'],
    'kings': ['knig', 'kin', 'king', 'kings', 'kinges','reg','ki','kins',
              'kng','kni','regu'],
    'lamentations': ['lament', 'lamentations', 'lam', 'la','lae',
                     'lamen','lamenta','lat','lan'],
    'leviticus': ['le', 'leuiticus', 'leuit', 'leu','l*uit','leui','leut'],
    'luke': ['luk', 'lk', 'lc', 'luke', 'luc','lucke','leuk',
             'l*c','l*k','l*uk','lok','luac','luca','luce','luck',
             'lukc','lukke'],
    'malachi': ['malac', 'ml', 'malach', 'mal', 'mala', 'malachi','malachie',
                'lach','m*l','m*lac','m*lach','ma','ma*ac','mach','mala*h',
                'malachie','malachy','mall','mallac','m'],
    'mark': ['mar', 'mr', 'marke', 'marc', 'mark','marg','mars',
             'm*k','m*r','m*rk','mak','march','marck','mork'],
    'matthew': ['mt', 'math', 'mattth', 'matthew', 'matt', 'matth', 
                'mat', 'mattb','mathew','mathewe','matthewe',
                'matthews','mattheuu','m*t','m*tth','ma*th',
                'maeth','mah','maith','mat*h','matht','matk'], # matthew's 
    'micah': ['mic', 'micah', 'mica', 'micha','m*cah','macah',
              'macha','mi','mic*h','micab','mich','mical','michah',
              'miche','michea','micheah','mieah','mieha','muc'],
    'nahum': ['nahum', 'nah', 'na','nahem','nahu','naum'],
    'nehemiah': ['nehem', 'nehemiah', 'ne', 'neh', 'nehe','nee',
                 'mehem','n*hem','neb','nehcm','nech','nehemi','nekem','neu'],
    'numbers': ['numbers', 'num', 'nu','numb', 'nm','n*m','nom','number',
                'nume','numer'],
    'obadiah': ['obadiah', 'obad', 'ob','obs','obediah'],
    'peter': ['peter', 'petr', 'pt', 'pet', 'pe','peters','peeter',
              'p*eter','peeters','pat','p*t','pete','pct','per','pot'],
    'philemon': ['pm', 'philemon', 'philem','p*ilemon','p*m'],
    # ambiguous phil 
    'philippians': ['phil', 'phi', 'philip','phillip', 'philippians', 
                    'philippe','p*ilip','phii','phiip','phili','philia',
                    'phill','philp','phl','phil','pil','plilip','thilip'],
    'proverbs': ['pro', 'prouerb', 'prou', 'pru', 'prouerbs', 'pou', 'pr',
                 'p*ou','pouer','pr*u','preu','pra','proer','prouer',
                 'prouorb','prow'],
    'psalms': ['psol', 'psl', 'psalm', 'pss', 'psa', 'psm', 'psal', 'ps', 
               'psalms', 'pslm', 'psalme','palm','pal','pasa','pasal',
               'pasl','pas','ps*l','ps*lm','psai','psam','psame',
               'psas','psay','psi','psil','psul','salm'],
    'revelation': ['reue', 'reuel', 're', 'apo', 'apoc', 'reuelations',
                   'reuelation', 'reu','apocalipse','apocal','apoca',
                   'reuelacion','apal','apho','aphor','apocalip','apocalips',
                    'apoe','apol','apoo','apos','apot','r*uel','rauel',
                    'reual','reuelat','reuil','reul','reule','reuol',
                    'reutl','rew','riuel','rouel','ruel'], 
                    # check apocalypse, apot, apos  
    'romans': ['ro', 'romans', 'roman', 'rom', 'rm','romaine','romane',
               'roma*','r*m','roma','rome','romi','room'],
    'ruth': ['ru', 'ruth','ruf'],
    'samuel': ['samuel', 'samuell', 'sm', 'sam','sa*uel','samuelles',
               'sumuel','s*m','s*muel','samu','samul','s'],
    'thessalonians': ['thes', 'thoss', 'thess', 'thessalonians', 'th', 'thss',
                      'tess','th*ss','the','thesa','thesi','thesl',
                      'thessa','thessal'],
    'timothy': ['timothy', 'tim', 'tom', 'timoth', 'timo','timothie','tome',
                'timothe','thom','ti','time','timi','timot','tims','tm'],
    'titus': ['tius', 'tit', 'titus','tis','ti*us','tirus','tite'], #"'tis"
    'tobit': ['tobi', 'tob', 'tobit','tobi*s','tobiae','toby'],
    'zechariah': ['zec', 'zachar', 'zech', 'zac', 'zechariah','zach',
                  'ze','zecha','zek','zach*','z*c','z*ch','z*char',
                  'za','za*har','zacb','zacha','zachary','zache',
                  'zack','zechar','zechat','zeck','zich','zoch','zsch'],
    'zephaniah': ['zeph', 'zep','zephaniah', 'zephan','zepha',
                  'zephany','zepho']
}

# dictionary mapping each abbreviation to its standard form 
abbrev_to_book = {}
for book, abbrev_list in abbrev.items():
    for a in abbrev_list: 
        abbrev_to_book[a] = book

# Turn the numbered books into one word for convenience in later regex tasks 
numBook = {
    '1 samuel':'onesamuel',
    '2 samuel':'twosamuel',
    '1 kings':'onekings',
    '2 kings':'twokings',
    '1 chronicles':'onechronicles',
    '2 chronicles':'twochronicles',
    '1 corinthians':'onecorinthians',
    '2 corinthians':'twocorinthians',
    '1 thessalonians':'onethessalonians',
    '2 thessalonians':'twothessalonians',
    '1 timothy':'onetimothy',
    '2 timothy':'twotimothy',
    '1 peter':'onepeter',
    '2 peter':'twopeter',
    '1 john':'onejohn',
    '2 john':'twojohn',
    '3 john':'threejohn'
}
